#!/bin/bash

# Builds and runs the game using the ghc's `runhaskell` command.
# The path following the -i flag is to specify the location of
# the necessary library files.

runhaskell -i/$(pwd)/src app/Main.hs
